# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 07:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=10)),
                ('memory', models.IntegerField(choices=[(16, b'16 GB'), (32, b'32 GB'), (64, b'64 GB')])),
                ('os', models.CharField(choices=[(b'Android', b'Android'), (b'IOS', b'IOS')], max_length=10)),
                ('ram', models.SmallIntegerField()),
                ('processor', models.CharField(max_length=30)),
                ('dimensions', models.CharField(max_length=30, null=True)),
                ('weight', models.IntegerField(null=True)),
                ('have_camera', models.NullBooleanField()),
                ('camera_front', models.IntegerField(null=True)),
                ('camera_back', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('display_name', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(choices=[(b'Shoes', b'Shoes'), (b'Mobiles', b'Mobiles')], max_length=30)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, default=b'', max_length=1000)),
                ('price', models.FloatField()),
                ('discount_amount', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=0)),
                ('quantity_available', models.IntegerField(blank=True, default=0)),
                ('units_on_order', models.IntegerField(blank=True, default=0)),
                ('in_stock', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime(2016, 10, 16, 7, 42, 30, 156349, tzinfo=utc))),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.IntegerField(default=0)),
                ('added_by', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField()),
                ('colour', models.CharField(max_length=10)),
                ('shoe_type', models.CharField(choices=[(b'SPORT', b'Sports'), (b'RUNNING', b'Running'), (b'CASUAL', b'Casuals'), (b'FORMAL', b'Formals'), (b'MOUNTAINEERING', b'Mountaineering')], default=b'RUNNING', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.Product')),
            ],
        ),
        migrations.AddField(
            model_name='mobiles',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.Product'),
        ),
    ]
