# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 07:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 10, 16, 7, 52, 15, 231817, tzinfo=utc)),
        ),
    ]
