# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 03:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0004_auto_20161012_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 10, 12, 3, 50, 58, 289026)),
        ),
    ]
