# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 06:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2016, 10, 11, 6, 11, 34, 430876)),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_on',
            field=models.DateField(default=datetime.datetime(2016, 10, 11, 6, 11, 34, 430910)),
        ),
        migrations.AlterField(
            model_name='phone',
            name='country_code',
            field=models.CharField(max_length=6),
        ),
    ]
