# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phone',
            unique_together=set([('country_code', 'mobile_no')]),
        ),
    ]
