# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 06:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161011_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2016, 10, 11, 6, 14, 7, 492312)),
        ),
        migrations.AlterField(
            model_name='address',
            name='pin_code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_on',
            field=models.DateField(default=datetime.datetime(2016, 10, 11, 6, 14, 7, 492345)),
        ),
        migrations.AlterField(
            model_name='phone',
            name='country_code',
            field=models.CharField(max_length=5),
        ),
    ]
