# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 06:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161011_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='address',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2016, 10, 11, 6, 47, 56, 541406)),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_on',
            field=models.DateField(default=datetime.datetime(2016, 10, 11, 6, 47, 56, 541441)),
        ),
    ]
