# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 08:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_auto_20161012_0738'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([('user', 'address')]),
        ),
        migrations.AlterUniqueTogether(
            name='phone',
            unique_together=set([('user', 'mobile_no')]),
        ),
    ]
